Update Dockerfile

diff --git a/CBIG/Dockerfile b/CBIG/Dockerfile
--- a/CBIG/Dockerfile
+++ b/CBIG/Dockerfile
@@ -1,31 +1,46 @@
-# Generated by: Neurodocker version 0.7.0
-# Latest release: Neurodocker version 0.7.0
-# Timestamp: 2021/05/12 17:55:10 UTC
-#
-# Thank you for using Neurodocker. If you discover any issues
-# or ways to improve this software, please submit an issue or
-# pull request on our GitHub repository:
-#
-#     https://github.com/ReproNim/neurodocker
+ARG MATLAB_RELEASE=r2022b
 
-FROM debian:stretch
+FROM mathworks/matlab-deps:${MATLAB_RELEASE}
 
 ENV http_proxy 'http://proxy.tch.harvard.edu:3128'
-ENV https_proxy 'http://proxy.tch.harvard.edu:3128'
-
-USER root
-
-ARG DEBIAN_FRONTEND="noninteractive"
+ENV  https_proxy 'http://proxy.tch.harvard.edu:3128'
 
 ENV LANG="en_US.UTF-8" \
     LC_ALL="en_US.UTF-8" \
     ND_ENTRYPOINT="/neurodocker/startup.sh"
-RUN export ND_ENTRYPOINT="/neurodocker/startup.sh"
-RUN apt-get update -qq
-RUN apt-get install -y -q --no-install-recommends \
+
+USER root
+
+##matlab
+ENV PATH="/opt/matlab:$PATH"
+RUN export DEBIAN_FRONTEND=noninteractive \
+    && apt-get update \
+    && apt-get install --no-install-recommends --yes \
+    wget \
+    unzip \
+    ca-certificates \
+    && apt-get clean \
+    && apt-get autoremove \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN wget -q https://www.mathworks.com/mpm/glnxa64/mpm \
+    && chmod +x mpm \
+    && ./mpm install \
+    --release=R2022b \
+    --destination=/opt/matlab \
+    --products MATLAB \
+    || (echo "MPM Installation Failure. See below for more information:" && cat /tmp/mathworks_root.log && false) \
+    && rm -f mpm /tmp/mathworks_root.log \
+    && ln -s /opt/matlab/bin/matlab /usr/local/bin/matlab
+
+COPY network.lic /opt/matlab/licenses/
+
+
+##CBIG dependencies
+RUN apt-get update -qq \
+    && apt-get install -y -q --no-install-recommends \
            apt-utils \
            bzip2 \
-           ca-certificates \
            curl \
            git \
            jq \
@@ -33,8 +48,11 @@ RUN apt-get install -y -q --no-install-recommends \
            nano \
            gnupg \
            gawk \
-           locales \
-           unzip
+           locales
+
+
+
+## Set up the entrypoint script $ND_ENTRYPOINT if it doesn't already exist
 RUN apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
     && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
@@ -48,15 +66,27 @@ RUN apt-get clean \
     &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
     &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
     fi \
-    && chmod -R 777 /neurodocker && chmod a+s /neurodocker \
-    && sed -i '$isource /BIDS_to_CBIG_fMRI_Preproc2016/CBIG_2BP_docker_config.sh' $ND_ENTRYPOINT
+    && chmod -R 777 /neurodocker && chmod a+s /neurodocker
 
+
+##create  directories for input and output data
+RUN mkdir -p /BIDS_input \
+    && mkdir -p /freesurfer_input \
+    && mkdir -p /output \
+    && mkdir -p /extra_files
+
+RUN wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.6_amd64.deb \
+    &&  dpkg -i multiarch-support_2.27-3ubuntu1.6_amd64.deb
+
+##install ANTS 2.20
 ENV ANTSPATH="/opt/ants-2.2.0" \
     PATH="/opt/ants-2.2.0:$PATH"
-RUN echo "Downloading ANTs ..."
-RUN mkdir -p /opt/ants-2.2.0
-RUN curl -fsSL --retry 5 https://dl.dropbox.com/s/2f4sui1z6lcgyek/ANTs-Linux-centos5_x86_64-v2.2.0-0740f91.tar.gz \
+
+RUN mkdir -p /opt/ants-2.2.0 \
+    && curl -fsSL --retry 5 https://dl.dropbox.com/s/2f4sui1z6lcgyek/ANTs-Linux-centos5_x86_64-v2.2.0-0740f91.tar.gz \
     | tar -xz -C /opt/ants-2.2.0 --strip-components 1
+
+
 
 ENV PATH="/opt/afni-latest:$PATH" \
     AFNI_PLUGINPATH="/opt/afni-latest"
@@ -76,9 +106,9 @@ RUN apt-get update -qq \
            xvfb \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
-    && curl -sSL --retry 5 -o /tmp/toinstall.deb http://mirrors.kernel.org/debian/pool/main/libx/libxp/libxp6_1.0.2-2_amd64.deb \
-    && dpkg -i /tmp/toinstall.deb \
-    && rm /tmp/toinstall.deb \
+    && wget http://ftp.debian.org/debian/pool/main/libx/libxp/libxp6_1.0.2-2_amd64.deb \
+    && dpkg -i libxp6_1.0.2-2_amd64.deb \
+    && rm libxp6_1.0.2-2_amd64.deb \
     && curl -sSL --retry 5 -o /tmp/toinstall.deb http://snapshot.debian.org/archive/debian-security/20160113T213056Z/pool/updates/main/libp/libpng/libpng12-0_1.2.49-1%2Bdeb7u2_amd64.deb \
     && dpkg -i /tmp/toinstall.deb \
     && rm /tmp/toinstall.deb \
@@ -95,6 +125,7 @@ RUN apt-get update -qq \
     && curl -fsSL --retry 5 http://afni.nimh.nih.gov/pub/dist/tgz/linux_openmp_64.tgz \
     | tar -xz -C /opt/afni-latest --strip-components 1
 
+##install FSL 5.0.10
 ENV FSLDIR="/opt/fsl-5.0.10" \
     PATH="/opt/fsl-5.0.10/bin:$PATH" \
     FSLOUTPUTTYPE="NIFTI_GZ" \
@@ -105,6 +136,7 @@ ENV FSLDIR="/opt/fsl-5.0.10" \
     FSLMACHINELIST="" \
     FSLREMOTECALL="" \
     FSLGECUDAQ="cuda.q"
+
 RUN apt-get update -qq \
     && apt-get install -y -q --no-install-recommends \
            bc \
@@ -114,8 +146,6 @@ RUN apt-get update -qq \
            libfreetype6 \
            libgl1-mesa-dev \
            libgl1-mesa-dri \
-           libglu1-mesa-dev \
-           libgomp1 \
            libice6 \
            libxcursor1 \
            libxft2 \
@@ -124,7 +154,6 @@ RUN apt-get update -qq \
            libxrender1 \
            libxt6 \
            sudo \
-           wget \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
     && echo "Downloading FSL ..." \
@@ -138,16 +167,14 @@ RUN apt-get update -qq \
     && echo "Installing FSL conda environment ..." \
     && bash /opt/fsl-5.0.10/etc/fslconf/fslpython_install.sh -f /opt/fsl-5.0.10
 
+
+##Install FreeSurfer 6.0.0
 ENV FREESURFER_HOME="/opt/freesurfer-6.0.0" \
     PATH="/opt/freesurfer-6.0.0/bin:$PATH"
 RUN apt-get update -qq \
     && apt-get install -y -q --no-install-recommends \
-           bc \
-           libgomp1 \
            libxmu6 \
-           libxt6 \
            perl \
-           tcsh \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* \
     && echo "Downloading FreeSurfer ..." \
@@ -168,6 +195,7 @@ RUN apt-get update -qq \
     && sed -i '$isource "/opt/freesurfer-6.0.0/SetUpFreeSurfer.sh"' "$ND_ENTRYPOINT" \
     && mkdir root/matlab && touch root/matlab/startup.m
 
+##install Connectome Workbench
 RUN echo "Downloading Connectome Workbench" \
     && wget -q -P /opt/ https://www.humanconnectome.org/storage/app/media/workbench/workbench-linux64-v1.5.0.zip \
     && cd /opt \
@@ -176,105 +204,37 @@ RUN echo "Downloading Connectome Workbench" \
     && cd \
     && apt-get update -qq \
     && apt-get install -y -q --no-install-recommends connectome-workbench \
+       libqt5core5a \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*
 
-ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu:/opt/matlabmcr-2021a/v94/runtime/glnxa64:/opt/matlabmcr-2021a/v94/bin/glnxa64:/opt/matlabmcr-2021a/v94/sys/os/glnxa64:/opt/matlabmcr-2021a/v94/extern/bin/glnxa64" \
-    MATLABCMD="/opt/matlabmcr-2021a/v94/toolbox/matlab"
-RUN export TMPDIR="$(mktemp -d)" \
-    && apt-get update -qq \
-    && apt-get install -y -q --no-install-recommends \
-            bc \
-            libncurses5 \
-            libxext6 \
-            libxmu6 \
-            libxpm-dev \
-            libxt6 \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/* \
-    && echo "Downloading MATLAB Compiler Runtime ..." \
-    && curl -fsSL --retry 5 -o "$TMPDIR/mcr.zip" https://ssd.mathworks.com/supportfiles/downloads/R2021a/Release/3/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2021a_Update_3_glnxa64.zip \
-    && unzip -q "$TMPDIR/mcr.zip" -d "$TMPDIR/mcrtmp" \
-    && "$TMPDIR/mcrtmp/install" -destinationFolder /opt/matlabmcr-2021a -mode silent -agreeToLicense yes \
-    && rm -rf "$TMPDIR" \
-    && unset TMPDIR
+ENV LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}"
 
-# RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash \
-    # && apt-get install git-lfs \
-    # && git lfs install
+RUN apt-get update && \
+    apt-get install -y binutils
+RUN strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 
+##BIDS_to_CBIG_fMRI_Preproc2016
 RUN mkdir -p /repos \
-    && git clone --depth 1 --branch compiled-for-MCR https://github.com/bchcohenlab/CBIG.git CBIG_compiled-for-MCR \
+    && git clone https://github.com/ThomasYeoLab/CBIG.git \
     && git clone https://github.com/bchcohenlab/BIDS_to_CBIG_fMRI_Preproc2016.git
 
-RUN mkdir -p /BIDS_input \
-    && mkdir -p /freesurfer_input \
-    && mkdir -p /output \
-    && mkdir -p /extra_files
 
-RUN chmod +x /CBIG_compiled-for-MCR/setup_docker_CBIG.sh \
-    && sed -i '$isource /CBIG_compiled-for-MCR/setup_docker_CBIG.sh' $ND_ENTRYPOINT
 
-ENTRYPOINT ["/neurodocker/startup.sh"]
+RUN chmod +x /BIDS_to_CBIG_fMRI_Preproc2016/BIDS_2BP_Thomas_docker_CBIG_fMRI_preprocess.sh \
+    && chmod +x /BIDS_to_CBIG_fMRI_Preproc2016/Thomas_CBIG_2BP_docker_config.sh   \
+    && sed -i '$isource /BIDS_to_CBIG_fMRI_Preproc2016/Thomas_CBIG_2BP_docker_config.sh' $ND_ENTRYPOINT
 
-CMD [“/BIDS_to_CBIG_fMRI_Preproc2016/CBIG_2BP_docker_config.sh \
-&& /BIDS_to_CBIG_fMRI_Preproc2016/BIDS_2BP_docker_CBIG_fMRI_preprocess.sh”]
 
 COPY license.txt /opt/freesurfer-6.0.0/license.txt
 
-RUN echo '{ \
-    \n  "pkg_manager": "apt", \
-    \n  "instructions": [ \
-    \n    [ \
-    \n      "base", \
-    \n      "debian:stretch" \
-    \n    ], \
-    \n    [ \
-    \n      "ants", \
-    \n      { \
-    \n        "version": "2.2.0", \
-    \n        "method": "binaries" \
-    \n      } \
-    \n    ], \
-    \n    [ \
-    \n      "afni", \
-    \n      { \
-    \n        "version": "latest", \
-    \n        "method": "binaries" \
-    \n      } \
-    \n    ], \
-    \n    [ \
-    \n      "fsl", \
-    \n      { \
-    \n        "version": "5.0.10" \
-    \n      } \
-    \n    ], \
-    \n    [ \
-    \n      "freesurfer", \
-    \n      { \
-    \n        "version": "6.0.0", \
-    \n        "method": "binaries" \
-    \n      } \
-    \n    ], \
-    \n    [ \
-    \n      "install", \
-    \n      [ \
-    \n        "connectome-workbench" \
-    \n      ] \
-    \n    ], \
-    \n    [ \
-    \n      "matlabmcr", \
-    \n      { \
-    \n        "version": "2021a", \
-    \n        "method": "binaries" \
-    \n      } \
-    \n    ], \
-    \n    [ \
-    \n      "spm12", \
-    \n      { \
-    \n        "version": "r7219", \
-    \n        "method": "binaries" \
-    \n      } \
-    \n    ] \
-    \n  ] \
-    \n}' > /neurodocker/neurodocker_specs.json
+COPY CBIG_preproc_native2mni.csh CBIG/stable_projects/preprocessing/CBIG_fMRI_Preproc2016/CBIG_preproc_native2mni.csh 
+RUN  chmod +x CBIG/stable_projects/preprocessing/CBIG_fMRI_Preproc2016/CBIG_preproc_native2mni.csh   
+
+
+RUN apt-get update && \
+    apt-get install -y bash && \
+    apt`-get install -y rsync 
+
+
+ENTRYPOINT ["/neurodocker/startup.sh"]
